services:
  web:
    build: .
    image: mp3-app:latest
    container_name: mp3-web
    ports:
      - "5050:5050"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5050 --workers 2 --timeout 300 app:app

  bot:
    image: mp3-app:latest
    container_name: mp3-bot
    depends_on:
      - web
    volumes:
      - ./logs:/app/logs
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: unless-stopped
    command: python bot.py
